export const AnimesList = [
  "Naruto",
  "Dragon Ball Z",
  "One Piece",
  "Attack on Titan",
  "My Hero Academia",
  "Death Note",
  "Fullmetal Alchemist: Brotherhood",
  "Sword Art Online",
  "Demon Slayer: Kimetsu no Yaiba",
  "One Punch Man",
  "Tokyo Ghoul",
  "Hunter x Hunter",
  "Fairy Tail",
  "Bleach",
  "Naruto Shippuden",
  "Neon Genesis Evangelion",
  "Code Geass",
  "Cowboy Bebop",
  "Black Clover",
  "JoJo's Bizarre Adventure",
  "Fruits Basket",
  "The Promised Neverland",
  "Attack on Titan: Junior High",
  "Haikyuu!!",
  "Sailor Moon",
  "Hunter x Hunter (2011)",
  "Mob Psycho 100",
  "Spirited Away",
  "Princess Mononoke",
  "Dragon Ball",
  "Your Lie in April",
  "The Seven Deadly Sins",
  "Assassination Classroom",
  "My Neighbor Totoro",
  "Akame ga Kill!",
  "Steins;Gate",
  "Dr. Stone",
  "Clannad",
  "The Rising of the Shield Hero",
  "Soul Eater",
  "Death Parade",
  "Boruto: Naruto Next Generations",
  "No Game No Life",
  "Dragon Ball Super",
  "KonoSuba: God's Blessing on This Wonderful World!",
  "Made in Abyss",
  "Fairy Tail (2014)",
  "Black Butler",
  "Kill la Kill",
  "Toradora!",
  "Fate/stay night",
  "Attack on Titan Season 3 Part 2",
  "Kimi no Na wa.",
  "Re:Zero - Starting Life in Another World",
  "Fate/Zero",
  "Akira",
  "Great Teacher Onizuka",
  "Naruto: Shippuden",
  "Howl's Moving Castle",
  "Digimon Adventure",
  "Blue Exorcist",
  "Parasyte -the maxim-",
  "Nisekoi: False Love",
  "Tokyo Ghoul:re",
  "Detective Conan",
  "K-On!",
  "Yu Yu Hakusho",
  "Space Dandy",
  "Inuyasha",
  "Pokemon",
  "Food Wars! Shokugeki no Soma",
  "Angel Beats!",
  "Anohana: The Flower We Saw That Day",
  "Attack on Titan Season 3 Part 1",
  "Psycho-Pass",
  "Bleach the Movie: Hell Verse",
  "High School DxD",
  "The Disastrous Life of Saiki K.",
  "High School of the Dead",
  "Violet Evergarden",
  "Gurren Lagann",
  "Dragon Ball GT",
  "Tokyo Ghoul: Jack",
  "The Melancholy of Haruhi Suzumiya",
  "Goblin Slayer",
  "Shokugeki no Souma: San no Sara - Tootsuki Ressha-hen",
  "Spice and Wolf",
  "Highschool of the Dead",
  "Elfen Lied",
  "Sakurasou no Pet na Kanojo",
  "Love Live! School Idol Project",
  "Noragami",
  "Tokyo Ghoul √A",
  "Is It Wrong to Try to Pick Up Girls in a Dungeon?",
  "Kill la Kill Special",
  "Vampire Knight",
  "Demon Slayer: Kimetsu no Yaiba - Mugen Train Arc",
  "Rosario + Vampire",
  "The Devil Is a Part-Timer!",
  "Tokyo Ghoul: Pinto",
  "The Ancient Magus' Bride",
  "Erased",
  "Inuyasha the Movie: Affections Touching Across Time",
  "Elfen Lied: In the Passing Rain",
  "The Future Diary",
  "Corpse Party: Tortured Souls",
  "High School DxD New",
  "Assassination Classroom the Movie: 365 Days' Time",
  "Is It Wrong to Try to Pick Up Girls in a Dungeon? II",
  "Gekkan Shoujo Nozaki-kun",
  "Devilman Crybaby",
  "K-On! Movie",
  "The Rising of the Shield Hero Season 2",
  "Attack on Titan Season 2",
  "Yuri!!! on Ice",
  "Toradora!: Bentou no Gokui",
  "Tokyo Ghoul: Jack Special",
  "Attack on Titan: Ilse's Notebook",
  "Guilty Crown",
  "Rascal Does Not Dream of Bunny Girl Senpai",
  "Attack on Titan: No Regrets",
  "Sword Art Online II",
  "Bunny Drop",
  "Attack on Titan Season 3",
  "Attack on Titan: Lost Girls",
  "Bakemonogatari",
];

export const scores = [9, 8, 7, 6, 5, 4, 3, 2];

export const seasons = [
  2024, 2023, 2022, 2021, 2020, 2019, 2018, 2017, 2016, 2015, 2014, 2013, 2012,
  2011, 2010, 2009, 2008, 2007, 2006, 2005, 2004, 2003, 2002, 2001, 2000,
];

export const status = ["upcoming", "airing", "complete"];

export const types = ["tv", "movie", "ova", "ona", "special"];

export const mangaTypes = [
  { name: "Manga", labe: "manga" },
  { name: "Novel", labe: "novel" },
  { name: "Light Novel", labe: "lightnovel" },
  { name: "Oneshot", labe: "oneshot" },
  { name: "Manhua", labe: "manhwa" },
  { name: "Manhwa", labe: "manhua" },
];
